### ISSUE TITLE
about compile

### ISSUE THREAD

**Issue by t2dk49580** [pureqml/qmlcore#145]
How to say, thank you for your efforts, but the compiled things still report various errors

my project have a img directory for the image

qml initialization failed:  Error: invalid property requested: 'img'
    at _globals.core.Image._globals.core.core.CoreObjectComponentPrototype._get (qml.main.js:422)
    at qml.main.js:3596
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.replaceUpdater (qml.main.js:607)
    at _globals.core.Image.ObjectPrototype._replaceUpdater (qml.main.js:1259)
    at _globals.src.IButtonText.IButtonTextPrototype.$s (qml.main.js:3596)
    at _globals.src.UiMain.UiMainPrototype.$s (qml.main.js:3171)
    at _globals.src.UiMain._globals.core.core.CoreObjectComponentPrototype.__init (qml.main.js:404)
    at _globals.core.Context.ContextPrototype.start (qml.main.js:4854)
    at qml.main.js:24937 Error: invalid property requested: 'img'
    at _globals.core.Image._globals.core.core.CoreObjectComponentPrototype._get (http://127.0.0.1/qcore/qml.main.js:422:9)
    at http://127.0.0.1/qcore/qml.main.js:3596:113
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.replaceUpdater (http://127.0.0.1/qcore/qml.main.js:607:2)
    at _globals.core.Image.ObjectPrototype._replaceUpdater (http://127.0.0.1/qcore/qml.main.js:1259:37)
    at _globals.src.IButtonText.IButtonTextPrototype.$s (http://127.0.0.1/qcore/qml.main.js:3596:24)
    at _globals.src.UiMain.UiMainPrototype.$s (http://127.0.0.1/qcore/qml.main.js:3171:24)
    at _globals.src.UiMain._globals.core.core.CoreObjectComponentPrototype.__init (http://127.0.0.1/qcore/qml.main.js:404:7)
    at _globals.core.Context.ContextPrototype.start (http://127.0.0.1/qcore/qml.main.js:4854:12)
    at http://127.0.0.1/qcore/qml.main.js:24937:10

[final.zip](https://github.com/pureqml/qmlcore/files/2637597/final.zip)

**Comment by t2dk49580** [comment]
I copy img directory in the build.web and always show the error, pls check it

**Comment by whoozle** [comment]
sorry I missed your issue somehow, did you fix it? Normally we have dist/ directory and everything from there preprocessed (html parsed as templates) and copied to resulting directory. You can even have a per-platform dist/ folders. 

Is it still an issue for you ?
