### ISSUE TITLE
Scope hierarchy not working

### ISSUE THREAD

**Issue by tomager** [pureqml/qmlcore#205]
I am wondering how to make hierarchical scoping work (it doesn't seem to), and if it doesn't whether a patch to implement it would be welcome. For example, in Qt QML I should be able to write something like:

```
Item {
    property color defaultColor: "blue";
    anchors.fill: context;

    ListView {
        model: ListModel {
            ListElement { value: "foo"; }
            ListElement { value: "bar"; }
            ListElement { value: "baz"; }
        }
        anchors.fill: parent;
        delegate: Rectangle {
            color: defaultColor;
            width: 100;
            height: 100;
            }
    }
}

```

and have defaultColor picked up from the outer scope. In pureqml this builds fine but then I get a runtime error of "invalid property requested defaultColor" (shown below). It works if I qualify the reference as `parent.parent.defaultColor`.

Thanks!

```
qml.app.js:1959 Context: initializing...
qml.app.js:5688 Context: window size: 394x656
qml.app.js:2003 Context: created instance
(index):42 Live reload enabled.
qml.app.js:1963 Context: signalling layout
qml.app.js:1966 Context: calling completed()
qml.app.js:1908 async action failed: Error: invalid property requested: 'defaultColor'
    at $core.Rectangle._globals.core.core.CoreObjectComponentPrototype._get (qml.app.js:440)
    at qml.app.js:2242
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.replaceUpdater (qml.app.js:636)
    at $core.Rectangle.ObjectPrototype._replaceUpdater (qml.app.js:1382)
    at $core.ListView.<anonymous> (qml.app.js:2242)
    at $core.ListView.BaseViewPrototype._createDelegate (qml.app.js:3080)
    at $core.ListView.ListViewPrototype._createDelegate (qml.app.js:3439)
    at $core.ListView.ListViewPrototype._layout (qml.app.js:3552)
    at $core.ListView.BaseLayoutPrototype._doLayout (qml.app.js:2622)
    at $core.Context.callback (qml.app.js:2039) Error: invalid property requested: 'defaultColor'
    at $core.Rectangle._globals.core.core.CoreObjectComponentPrototype._get (http://172.22.162.66:8080/qml.app.js:440:9)
    at http://172.22.162.66:8080/qml.app.js:2242:78
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.replaceUpdater (http://172.22.162.66:8080/qml.app.js:636:2)
    at $core.Rectangle.ObjectPrototype._replaceUpdater (http://172.22.162.66:8080/qml.app.js:1382:37)
    at $core.ListView.<anonymous> (http://172.22.162.66:8080/qml.app.js:2242:13)
    at $core.ListView.BaseViewPrototype._createDelegate (http://172.22.162.66:8080/qml.app.js:3080:15)
    at $core.ListView.ListViewPrototype._createDelegate (http://172.22.162.66:8080/qml.app.js:3439:55)
    at $core.ListView.ListViewPrototype._layout (http://172.22.162.66:8080/qml.app.js:3552:18)
    at $core.ListView.BaseLayoutPrototype._doLayout (http://172.22.162.66:8080/qml.app.js:2622:8)
    at $core.Context.callback (http://172.22.162.66:8080/qml.app.js:2039:11)
qml.app.js:1908 async action failed: Error: invalid property requested: 'defaultColor'
    at $core.Rectangle._globals.core.core.CoreObjectComponentPrototype._get (qml.app.js:440)
    at qml.app.js:2242
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.replaceUpdater (qml.app.js:636)
    at $core.Rectangle.ObjectPrototype._replaceUpdater (qml.app.js:1382)
    at $core.ListView.<anonymous> (qml.app.js:2242)
    at $core.ListView.BaseViewPrototype._createDelegate (qml.app.js:3080)
    at $core.ListView.ListViewPrototype._createDelegate (qml.app.js:3439)
    at $core.ListView.ListViewPrototype._layout (qml.app.js:3552)
    at $core.ListView.BaseLayoutPrototype._doLayout (qml.app.js:2622)
    at $core.Context.callback (qml.app.js:2039) Error: invalid property requested: 'defaultColor'
    at $core.Rectangle._globals.core.core.CoreObjectComponentPrototype._get (http://172.22.162.66:8080/qml.app.js:440:9)
    at http://172.22.162.66:8080/qml.app.js:2242:78
    at PropertyStorage._globals.core.core.PropertyStoragePrototype.replaceUpdater (http://172.22.162.66:8080/qml.app.js:636:2)
    at $core.Rectangle.ObjectPrototype._replaceUpdater (http://172.22.162.66:8080/qml.app.js:1382:37)
    at $core.ListView.<anonymous> (http://172.22.162.66:8080/qml.app.js:2242:13)
    at $core.ListView.BaseViewPrototype._createDelegate (http://172.22.162.66:8080/qml.app.js:3080:15)
    at $core.ListView.ListViewPrototype._createDelegate (http://172.22.162.66:8080/qml.app.js:3439:55)
    at $core.ListView.ListViewPrototype._layout (http://172.22.162.66:8080/qml.app.js:3552:18)
    at $core.ListView.BaseLayoutPrototype._doLayout (http://172.22.162.66:8080/qml.app.js:2622:8)
    at $core.Context.callback (http://172.22.162.66:8080/qml.app.js:2039:11)

```

**Comment by tomager** [comment]
The patch below generates what I think is the correct behavior. The Qt docs discuss this at [1]. If something like this is agreeable, I am happy to submit a pull request or develop it further with some guidance.

```
diff --git a/core/core.js b/core/core.js                                                                              |        }
index 373ea30e..af549d3b 100644                                                                                       |        var triplet
--- a/core/core.js                                                                                                    |        if (value[0] === '#') {
+++ b/core/core.js                                                                                                    |                triplet = value.substring(1)
@@ -258,6 +258,9 @@ CoreObjectComponentPrototype._get = function(name, unsafe) {                                      |        } else if (value.substring(0, 4) === "rgba") {
        if (name in this._local)                                                                                      |                var b = value.indexOf('('), e = value.lastIndexOf(')')
                return this._local[name]                                                                              |                value = value.substring(b + 1, e).split(',')
                                                                                                                      |                this.r = parseInt(value[0], 10)
+        if (this.parent)                                                                                             |                this.g = parseInt(value[1], 10)
+               return this.parent._get(name, unsafe)                                                                 |                this.b = parseInt(value[2], 10)
+                                                                                                                     |                this.a = Math.floor(parseFloat(value[3]) * 255)
        if (unsafe)                                                                                                   |                return
                return null                                                                                           |        } else
        else                                                                                                          |                triplet = colorTable[value]

```

[1] https://doc.qt.io/qt-5/qtqml-documents-scope.html#component-instance-hierarchy

**Comment by tomager** [comment]
One problem with above patch is that a change of the parent property doesn't cause proper update to layout.

For example, in the below example the list item rectangles only update their layout when the `parent.parent.w0` form is used. A reference of `w0` causes it to be correct on first use but then does not update if you resize the browser window.

```
Item {
    property color defaultColor: "blue";
    anchors.fill: context;

    property int w0: width/5;

    ListView {
        model: ListModel {
            ListElement { value: "foo"; }
            ListElement { value: "bar"; }
            ListElement { value: "baz"; }
        }
        anchors.fill: parent;
        delegate: Rectangle {
            color: "red";
            width: parent.parent.w0;
            height: parent.parent.w0;
            Rectangle {
                anchors.margins: 10;
                anchors.fill: parent;
                color: defaultColor;
                Text {
                    anchors.centerIn: parent;
                    color: "white";
                    text: model.value + " " + parent.parent.parent.parent.w0;
                }
                width: 100;
                height: 100;
            }
        }
    }
}

```

**Comment by tomager** [comment]
Okay, the below change does both the get path as as well as the callback path.

```
diff --git a/core/core.js b/core/core.js
index 373ea30e..7ff04554 100644
--- a/core/core.js
+++ b/core/core.js
@@ -258,6 +258,9 @@ CoreObjectComponentPrototype._get = function(name, unsafe) {
        if (name in this._local)
                return this._local[name]

+        if (this.parent)
+               return this.parent._get(name, unsafe)
+
        if (unsafe)
                return null
        else
@@ -454,7 +457,14 @@ PropertyStoragePrototype.replaceUpdater = function(parent, callback, deps) {
        var connectOnChanged = parent.connectOnChanged
        for(var i = 0, n = deps.length; i < n; i += 2) {
                var object = deps[i]
-               var name = deps[i + 1]
+           var name = deps[i + 1]
+
+           while (object &&
+                  object.parent &&
+                  !(name in object) &&
+                 !(name in object._local))
+               object = object.parent;
+
                connectOnChanged.call(parent, object, name, callback)
        }
        callback()

```

This example now works as expected:

```
Item {
    property color defaultColor: "blue";
    anchors.fill: context;

    property int w0: width/5;

    ListView {
        model: ListModel {
            ListElement { value: "foo"; }
            ListElement { value: "bar"; }
            ListElement { value: "baz"; }
        }
        anchors.fill: parent;
        delegate: Rectangle {
            color: "red";
            width: w0;
            height: w0;
            Rectangle {
                anchors.margins: 10;
                anchors.fill: parent;
                color: defaultColor;
                Text {
                    anchors.centerIn: parent;
                    color: "white";
                    text: model.value + " " + w0;
                }
                width: 100;
                height: 100;
            }
        }
    }
}

```

**Comment by whoozle** [comment]
Hello, @tomager 

Thanks for the effort, it's really impressive you can figure out how to resolve it in runtime.

Unfortunately we can't do it in runtime because of performance reasons. Pureqml compiler always resolves all properties statically at compile time. This was design decision that made pureqml very fast (and we have *really* old platforms, from pre-bind era you may imagine what the performance of the engines there). We only allow dynamic id lookup because it happens only when handler fired/expression re-evaluated, and it has only O(depth) complexity.
  
However the idea is nice, we're trying to use nice features of original QML. And I think it's pretty much possible to do.
Currently we're using explicit `<parent>.<parent>.property` lookups, and this is a bit ugly, I agree.

`Component.find_property` is a good place to start with:
https://github.com/pureqml/qmlcore/blob/master/compiler/js/component.py#L443

I can implement it for you, but I think it will take some time. 

Thank for insterest and the effort again, have fun! :)

**Comment by tomager** [comment]
I see-- okay, here's another attempt that does it statically. The component generators don't seem to track their parents, so I added that on the add_child path, and then use it as a special case that is enabled for length-1 paths in parse_deps. It's a bit fussy around parse_deps, but as is it's a fairly narrow change.

The example [2] works as expected, and for example generates [1] for the inner width and height fields.

Let me know if you want changes and/or pull request.

Also, thank you for your work on this amazing framework! I feel like this is the way Qt should have gone with their Qt for WebAssembly [4] work, with wasm used for C++ side plugins within PureQML components etc. Maybe PureQML can be upstreamed into Qt in the future. The current Qt wasm approach is far too heavy-- PureQML model is the right way.

[1]
```
//assigning width to (${w0})
                        delegate._replaceUpdater('width', function() { delegate.width = (delegate.parent.parent.w0) }, [delegate.parent.parent,'w0'])
//assigning height to (${parent.parent.w0})
                        delegate._replaceUpdater('height', function() { delegate.height = (delegate.parent.parent.w0) }, [delegate.parent.parent,'w0'])

```

[2]
```
Item {
    anchors.fill: context;
    property color defaultColor: "blue";
    Rectangle {
        anchors.fill: parent;
        color: parent.defaultColor;
    }

    property int w0: width/5;

    ListView {
        model: ListModel {
            ListElement { value: "foo"; }
            ListElement { value: "bar"; }
            ListElement { value: "baz"; }
        }
        anchors.fill: parent;
        delegate: Rectangle {
            color: defaultColor;
            width: w0;
            height: parent.parent.w0;
            Rectangle {
                anchors.margins: 10;
                anchors.fill: parent;
                color: "red";
                Text {
                    anchors.centerIn: parent;
                    color: "white";
                    text: model.value + " " + w0;
                }
                width: 100;
                height: 100;
            }
        }
    }

}

```

[3]
```
diff --git a/compiler/js/code.py b/compiler/js/code.py
index 690d5ea2..2ae77c23 100644
--- a/compiler/js/code.py
+++ b/compiler/js/code.py
@@ -35,8 +35,8 @@ def process(text, generator, registry, args):
 	#print text
 	return text
 
-def mangle_path(path, transform):
-	path = [transform(path[0])] + path[1:]
+def mangle_path(path, transform, hier=False):
+	path = [transform(path[0], hier=hier)] + path[1:]
 	return '.'.join(path)
 
 def path_or_parent(path, parent, transform):
@@ -57,6 +57,16 @@ def parse_deps(parent, text, transform):
 		path = m.group(1).split('.')
 		target = path[-1]
 		gets = path[:-1]
+
+		#if the path is only a single component, try hierarchical scoping
+		if len(path) == 1:
+			tpath = mangle_path(path, transform, hier=True)
+			tpath_v = tpath.split('.')
+			if target != 'parent':
+				tdep = parent + "." + '.'.join(tpath_v[:-1]) if len(tpath_v)>1 else parent
+				deps.add((tdep, target))
+			return parent + '.' + tpath
+		
 		if len(path) > 1 and path[0] == 'manifest':
 			return '$' + '$'.join(path)
 		if len(path) > 1 and path[0] == 'model':
diff --git a/compiler/js/component.py b/compiler/js/component.py
index 15aabd91..c0263dd1 100644
--- a/compiler/js/component.py
+++ b/compiler/js/component.py
@@ -9,9 +9,10 @@ from functools import partial
 import re
 
 class component_generator(object):
-	def __init__(self, ns, name, component, prototype = False):
+	def __init__(self, ns, parent_generator, name, component, prototype = False):
 		self.ns = ns
 		self.name = name
+		self.parent_generator = parent_generator
 		self.component = component
 		self.aliases = {}
 		self.declared_properties = {}
@@ -69,7 +70,7 @@ class component_generator(object):
 			g.collect_id(id_set)
 
 	def create_component_generator(self, component, suffix = '<anonymous>'):
-		value = component_generator(self.ns, self.package + "." + suffix, component)
+		value = component_generator(self.ns, self, self.package + "." + suffix, component)
 		self.generators.append(value)
 		return value
 
@@ -77,6 +78,7 @@ class component_generator(object):
 		t = type(value)
 		if t is lang.Component:
 			value = self.create_component_generator(value)
+			#print("dep %s:%s.%s -> %s:%s" % (hex(id(self)),self.component.name, target, hex(id(value)),value.component.name))
 		if isinstance(value, (str, basestring)): #and value[0] == '"' and value[-1] == '"':
 			value = str(value.replace("\\\n", "")) #multiline continuation \<NEWLINE>
 		if target in self.assignments:
@@ -100,7 +102,9 @@ class component_generator(object):
 						raise Exception("lazy property must be declared with component as value")
 					if len(child.properties) != 1:
 						raise Exception("property %s is lazy, hence should be declared alone" %name)
-					self.lazy_properties[name] = self.create_component_generator(default_value, '<lazy:%s>' %name)
+					value = self.create_component_generator(default_value, '<lazy:%s>' %name)
+					#print("dep %s:%s.%s -> %s:%s" % (hex(id(self)),self.component.name, name, hex(id(value)),value.component.name))
+					self.lazy_properties[name] = value
 
 				if child.const:
 					if len(child.properties) != 1:
@@ -128,12 +132,14 @@ class component_generator(object):
 			self.assign("id", child.name)
 		elif t is lang.Component:
 			value = self.create_component_generator(child)
+			#print("dep %s:%s.<anonymous> -> %s:%s" % (hex(id(self)), self.component.name, hex(id(value)),value.component.name))
 			self.children.append(value)
 		elif t is lang.Behavior:
 			for target in child.target:
 				if target in self.animations:
 					raise Exception("duplicate animation on property " + target)
 				value = self.create_component_generator(child.animation, "<anonymous-animation>")
+				#print("dep %s:%s.%s -> %s:%s" % (hex(id(self)), self.component.name, target, hex(id(value)),value.component.name))
 				self.animations[target] = value
 		elif t is lang.Method:
 			for name in child.name:
@@ -542,7 +548,7 @@ class component_generator(object):
 
 		return "\n".join(r)
 
-	def transform_root(self, registry, parent, property):
+	def transform_root(self, registry, parent, property, hier=False):
 		if property == 'context':
 			return ("%s._get('%s')" %(parent, property)) if parent else '_context'
 		elif property == 'parent':
@@ -552,6 +558,17 @@ class component_generator(object):
 			if prop:
 				return property
 			else:
+				if hier:
+					#try to find property in parent generators
+					g = self.parent_generator
+					prefix = "parent."
+					while g:
+						prop = g.find_property(registry, property)
+						if prop:
+							return prefix + property
+						prefix += "parent."
+						g = g.parent_generator
+				
 				#replace first id (not a property with parent object reference)
 				return ("%s._get('%s')" %(parent, property)) if parent else ("_get('%s')" %property)
 
diff --git a/compiler/js/generator.py b/compiler/js/generator.py
index 17988528..b40ce84f 100644
--- a/compiler/js/generator.py
+++ b/compiler/js/generator.py
@@ -44,7 +44,7 @@ class generator(object):
 			self.packages[package] = set()
 		self.packages[package].add(component_name)
 
-		gen = component_generator(self.ns, name, component, True)
+		gen = component_generator(self.ns, None, name, component, True)
 		self.components[name] = gen
 
 	def add_js(self, name, data):

```

[4] https://doc.qt.io/qt-5/wasm.html

**Comment by whoozle** [comment]
Yes, definitely we want this! 
Could you rename `parent_generator` to just `parent` please and I think you meant heir, not hier?

**Comment by tomager** [comment]
Super, will submit a pull request shortly with parent renamed. I meant hier, as shortening of hierarchical.

**Comment by whoozle** [comment]
maybe rename it to something more readable then, like `lookup_parent` or something like that
